version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:v2.30.0
    container_name: filebrowser
    ports:
      - <"xxxx:xx">
    volumes:
      - /home/thibaut/donnees_nas:/srv
      - ./filebrowser.db:/database/filebrowser.db
    restart: always



