services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: <xxxx>
      PGID: <xxxx>
      HOMEPAGE_ALLOWED_HOSTS: <xxx.xxx.xxx.xxx:xxxx>
    ports:
      - <XXXX:XXXX>
    volumes:
      - /home/thibaut/docker/homepage/images:/app/public/images
      - /home/thibaut/docker/homepage/icons:/app/public/icons
      - /home/thibaut/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
